version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - node/install:
          node-version: "16.15"
      - checkout
      - run:
          name: Install EB
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python-dev build-essential
            sudo pip install --upgrade setuptools
            sudo pip install awsebcli --upgrade
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "Install dependencies in the the Front-end ... "
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
      - run:
          name: Install API Dependencies
          command: |
            echo "Install dependencies in the the backend API ... "
             echo "NODE --version" 
             echo $(node --version)
             echo "NPM --version" 
             echo $(npm --version)
            npm run api:install
      - run:
          name: Front-End Build
          command: |
            echo "Build the Front-End"
            npm run frontend:build
      - run:
          name: API Build
          command: |
            echo "TODO: Build the backend API"
            npm run api:build
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: "16.15"
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Deploy App
          command: |
            npm run deploy

workflows:
  udagram:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
